Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)

# Section A *(2 Marks each)*

## NumPy (Numerical Python)

---



---


**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways 
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**

In [ ]:
import numpy as np

In [61]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it 
one_dim = [1, 2, 3, 4, 5]
array= np.array(one_dim)
print(array)


# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it 
two_dim = [[1, 2, 3], [1, 2, 3], [1, 2, 3]]
array = np.array(two_dim)
print(array)

[1 2 3 4 5]
[[1 2 3]
 [1 2 3]
 [1 2 3]]

In [26]:

one_dim = [1, 2, 3, 4, 5]
array= np.array(one_dim)
print(array)

[1 2 3 4 5]

In [27]:

two_dim = [[1, 2, 3], [1, 2, 3], [1, 2, 3]]
array = np.array(two_dim)
print(array)

[[1 2 3]
 [1 2 3]
 [1 2 3]]

In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]

In [28]:

def create_random_array(rows, columns):
    return np.random.random((rows, columns))

some_array = create_random_array(3, 4)
print(some_array)

[[0.11202095 0.77029888 0.26256249 0.69305514]
 [0.871537   0.78621553 0.44032041 0.8367846 ]
 [0.03060993 0.09961671 0.77758674 0.8596033 ]]

In [29]:


def create_zeros_array(rows, columns):
    return np.zeros((rows, columns))

some_array = create_zeros_array(3, 4)
print(some_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In [30]:
 

def create_ones_array(rows, columns):
    return np.ones((rows, columns))

some_array = create_ones_array(3, 4)
print(some_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace

In [31]:
a= np.arange(2,20,2)
print(a)

[ 2  4  6  8 10 12 14 16 18]

### Basic array operations
- algebraic operations 
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'

In [38]:
def array_arithmetic(a, b):
    print("Addition")
    print(np.add(a, b))

    print("Subtraction")
    print(np.subtract(a, b))

    print("Multiplication")
    print(np.multiply(a, b))

    print("Division")
    print(np.divide(a, b))
    
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
array_arithmetic(a, b)

Addition
[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
Subtraction
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
Multiplication
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
Division
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]

In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0 

# Write a NumPy function to get the sum of the array 'a' along axis=1

In [41]:
def sum_along_axis_zero(a):
    return np.sum(a, axis=0)
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
sum_along_axis_zero(a)

array([ 6, 17, 14])

In [42]:
def sum_along_axis_one(a):
    return np.sum(a, axis=1)
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
sum_along_axis_one(a)

array([10, 13, 14])

In [ ]:
# Write a NumPy function to reverse the array 'a' 

# Write a NumPy function to reverse the array 'a' along axis=0

# Write a NumPy function to reverse the array 'a' along axis=1

In [43]:
def reverse_array(a):
    return np.flip(a)
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
reverse_array(a)

array([[ 5,  8,  1],
       [ 1,  3,  9],
       [ 8,  6, -4]])

In [44]:
def reverse_array_along_axis_zero(a):
    return np.flip(a, axis=0)
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
reverse_array_along_axis_zero(a)

array([[ 1,  8,  5],
       [ 9,  3,  1],
       [-4,  6,  8]])

In [45]:
def reverse_array_along_axis_one(a):
    return np.flip(a, axis=1)
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
reverse_array_along_axis_one(a)

array([[ 8,  6, -4],
       [ 1,  3,  9],
       [ 5,  8,  1]])

### Sorting and concatenation
- sort arrays
- join multiple arrays

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a' 

# Write a NumPy function to sort the array 'a' along axis=0

# Write a NumPy function to sort the array 'a' along axis=1

# Write a NumPy function to sort the array 'a' in descending order along axis=0

In [46]:
def sort_array(a):
    return np.sort(a)
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])   
sort_array(a)

array([[-4,  6,  8],
       [ 1,  3,  9],
       [ 1,  5,  8]])

In [47]:
def sort_array_along_axis_zero(a):
    return np.sort(a, axis=0)
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])   
sort_array_along_axis_zero(a)

array([[-4,  3,  1],
       [ 1,  6,  5],
       [ 9,  8,  8]])

In [48]:
def sort_array_along_axis_one(a):
    return np.sort(a, axis=1)
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])   
sort_array_along_axis_one(a)

array([[-4,  6,  8],
       [ 1,  3,  9],
       [ 1,  5,  8]])

In [ ]:
# Write a NumPy function to argsort the array along axis=0

# Write a NumPy function to argsort the array along axis=1

In [52]:
def argsort_array_along_axis_zero(a):
    return np.argsort(a,axis=0)
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])   
argsort_array_along_axis_zero(a)

array([[0, 1, 1],
       [2, 0, 2],
       [1, 2, 0]])

In [53]:
def argsort_array_along_axis_one(a):
    return np.argsort(a,axis=1)
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])   
argsort_array_along_axis_one(a)

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1]])

In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0

# Note: You can do the same function using stacking, discover and try that :)

In [57]:
def concatenate_arrays(a, b): 
   return np.concatenate((a, b))

a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

concatenate_arrays(a, b)

array([[-4,  6,  8],
       [ 9,  3,  1],
       [ 1,  8,  5],
       [11, 16, 18],
       [90, 37, 81],
       [61, 48, 75]])

In [58]:
def concatenate_arrays_along_axis_zero(a, b): 
   return np.concatenate((a, b), axis=0)

a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

concatenate_arrays_along_axis_zero(a, b)

array([[-4,  6,  8],
       [ 9,  3,  1],
       [ 1,  8,  5],
       [11, 16, 18],
       [90, 37, 81],
       [61, 48, 75]])

### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [59]:
# Write a NumPy function to get the Number of dimensions
def get_numpy_dim(a):
    return a.ndim
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])  
get_numpy_dim(a)

2

In [62]:
# Write a NumPy function to get the Shape of the array 
def get_array_shape(a):
    return a.shape
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])  
get_array_shape(a)

(3, 3)

In [63]:
# Write a NumPy function to get the Size of the array
def get_array_size(a):
    return a.size
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])  
get_array_size(a)

9

In [66]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
def array_reshape(a):
    return a.reshape(1,9)
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])  
array_reshape(a)

array([[4, 6, 8, 9, 3, 1, 1, 8, 5]])

In [67]:
# Write a NumPy function to add a new axis to the array 'a' 
# Note : Show atleast two different ways of doing this 

def add_new_axis(a):
    return a[np.newaxis, :]
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])  
add_new_axis(a)

array([[[4, 6, 8],
        [9, 3, 1],
        [1, 8, 5]]])

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [69]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
def index_and_slice_array(a):
    # indexing with an integer
    print("a[0] = ", a[0])
    
    # indexing with a tuple
    print("a[0, 1] = ", a[0, 1])
    
    # using range
    print("a[0:2, 1:3] = ", a[0:2, 1:3])

a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
index_and_slice_array(a)

a[0] =  [4 6 0]
a[0, 1] =  6
a[0:2, 1:3] =  [[6 0]
 [3 1]]

In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4 

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2

In [71]:
def select_values_greater_than_4(a):
    x = a[a>4]
    return x
def select_values_greater_than_4_and_divisible_by_2(a):
    y = a[(a>4) & (a%2 ==0)]
    return y
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
x = select_values_greater_than_4(a)
print(" Values greater than 4", x)
y = select_values_greater_than_4_and_divisible_by_2(a)
print(" Values greater than 4 and divisible by 2", y)

 Values greater than 4 [6 8 5]
 Values greater than 4 and divisible by 2 [6 8]

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [73]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
def copy_and_inc_by_one(a):
    b= np.copy(a)
    b += 1
    return b
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
b = copy_and_inc_by_one(a)
print(b)

[[5 7 1]
 [1 4 2]
 [2 9 6]]

## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.

#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
import pandas as pd

In [75]:
# Write a Pandas function to drop rows that contain a missing value. 
def drop_missing_rows(df):
    df.dropna(inplace=True)
    return df

In [74]:
# Write a Pandas function to find the correlation between the first two columns.
def find_correlation(df):
    df_subset = df.iloc[:, :2]
    correlation = df_subset.corr()
    return correlation.iloc[0,1]

In [76]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
def find_stats(df):
    col_3 = df.iloc[:, 2]
    mean = col_3.mean()
    median = col_3.median()
    std_dv = col_3,std()
    return {'mean': mean, 'median': median, 'standard deviation': std_dv}

In [77]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints: 
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

def add_volume_column(df):
    volume = (np.pi * df['petal_length'] * (df['sepal_length'] ** 2)) / 3
    df['volume'] = volume
    return df

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [78]:
import numpy as np

def ones_like_x(x):
   ones_array = np.ones_like(x)
   return ones_array
x = np.arange(4, dtype=np.int64)
a = ones_like_x(x)   
print(a)

[1 1 1 1]

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [79]:
import numpy as np

def split_x():
    x = np.arange(1,10) 
    split_array = np.split(x,[4,6])
    return split_array
split_array = split_x()  
print(split_array)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [82]:
def max_min_indices_x():
    x = np.random.uniform(0, 10, size=(2, 5))
    max_v = np.amax(x, axis=1)
    max_i = np.argmax(x, axis=1)
    min_v = np.amin(x, axis=1)
    min_i = np.argmin(x, axis=1)
    return max_v, max_i, min_v, min_i
max_v, max_i, min_v, min_i = max_min_indices_x()
print("Max values along the second axis",max_v,)   
print("Indices of Max values along the second axis", max_i)
print("Max values along the second axis", min_v)
print("Indices of Max values along the second axis", min_i)

Max values along the second axis [9.84006043 6.03823451]
Indices of Max values along the second axis [3 0]
Max values along the second axis [0.67053692 0.86307951]
Indices of Max values along the second axis [4 4]

### Pandas

Run the following load command and solve the following questions

In [85]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [83]:
def count_unique_species(df):
  count = df['species'].nunique()
  return count

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [84]:
def bin_petal_length(iris_2d):
    bins = [0, 3, 5, float("inf")]
    labels = ["small", "medium", "large"]
    iris_2d['petal_length_category'] = pd.cut(iris_2d['petal_length'], bins=bins, labels=labels)
    return iris_2d

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [86]:
def most_frequent_petal_length(df):
   mode = df['petal_lenght'].mode()
   return mode[0]